quadruped_controller:
  ros__parameters:
    type: quadruped_ros2_control/QuadrupedController
    joints:
      - RF_HAA
      - LF_HAA
      - RH_HAA
      - LH_HAA
      - RF_HFE
      - LF_HFE
      - RH_HFE
      - LH_HFE
      - RF_KFE
      - LF_KFE
      - RH_KFE
      - LH_KFE

    command_interfaces:
      - effort

    state_interfaces:
      - effort
      - position
      - velocity