# Controller Manager configuration
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true  # If running in simulation

    # Define the available controllers
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster